apiVersion: apps/v1
kind: Deployment
metadata:
  name: single-pixel-go
  labels:
    app: single-pixel-go
spec:
  replicas: 1
  selector:
    matchLabels:
      app: single-pixel-go
  template:
    metadata:
      labels:
        app: single-pixel-go
    spec:
      containers:
        - name: single-pixel-go
          image: ghcr.io/jafossum/blinkt-single-pixel-go:latest
          env:
            - name: BRIGHTNESS_1
              value: "0"
            - name: BRIGHTNESS_2
              value: "128"
            - name: BRIGHTNESS_3
              value: "0"
          volumeMounts:
            - mountPath: /home/pi/pixels
              name: dir
          securityContext:
            privileged: true
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: dir
          hostPath:
            path: /home/pi/pixels
            type: DirectoryOrCreate
