apiVersion: apps/v1
kind: Deployment
metadata:
  name: faas-simple-flask
  labels:
    app: faas-simple-flask
spec:
  replicas: 4
  selector:
    matchLabels:
      app: faas-simple-flask
  template:
    metadata:
      labels:
        app: faas-simple-flask
    spec:
      containers:
        - name: faas-simple-flask
          image: jafossum/faas-simple-flask:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: faas-simple-flask-service
spec:
  selector:
    app: faas-simple-flask
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
