
apiVersion: apps/v1
kind: Deployment
metadata:
  name: single-pixel
  labels:
    app: single-pixel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: single-pixel
  template:
    metadata:
      labels:
        app: single-pixel
    spec:
      containers:
      - name: single-pixel
        image: jafossum/blinkt-single-pixel:latest
        volumeMounts:
        - mountPath: /home/pi/pixels
          name: dir
        securityContext:
          privileged: true
      imagePullSecrets:
      - name: regcred
      volumes:
      - name: dir
        hostPath:
          path: /home/pi/pixels
          type: DirectoryOrCreate
