apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  labels:
    app: web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels: 
        app: web-app
    spec:
      containers:
      - name: web-app
        image: jafossum/web-app-blinkt:latest
        ports:
        - containerPort: 8081
        env:
        - name: MONGODB_ADMINUSERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-username
        - name: MONGODB_ADMINPASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-password
        - name: MONGODB_SERVER
          valueFrom:
            configMapKeyRef:
              name: mongodb-configmap
              key: database_url
        volumeMounts:
        - mountPath: /home/pi/pixels
          name: dir 
      volumes:
      - name: dir
        hostPath:
          path: /home/pi/pixels
          type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata: 
  name: web-app-service
spec:
  selector:
    app: web-app
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
    nodePort: 30000

